### ISSUE TITLE
Missing file extension

### ISSUE THREAD

**Issue by SecsAndCyber** [vrtadmin/FIRST-server#2]
$ cd FIRST-server/server/utilities
$ python engine_shell install first.engines.exact_match ExactMatchEngine <developer_email>
$ python engine_shell install first.engines.mnemonic_hash MnemonicHashEngine <developer_email>
$ python engine_shell install first.engines.basic_masking BasicMaskingEngine <developer_email>

engine_shell is actually engine_shell.py

**Comment by demonduck** [comment]
Docs updated. Thanks for creating this issue :)
