### ISSUE TITLE
Add users by CLI

### ISSUE THREAD

**Issue by SecsAndCyber** [vrtadmin/FIRST-server#3]
Currently there is not a streamlined way to use FIRST locally without OAuth.

Add a FIRST-server/server/utilities script to allow command line creation of new users

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
python manage.py shell
n = first.models.User(.........)
n.save()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by demonduck** [comment]
Commit 422fd27 contains a User management shell. See `FIRST-server/server/utilities/user_shell.py`
