### ISSUE TITLE
Missing google_secret.json blocks docker-compose

### ISSUE THREAD

**Issue by SecsAndCyber** [vrtadmin/FIRST-server#4]
COPY install/google_secret.json /usr/local/etc

there is no install/google_secret.json in the repo so the above line terminates the build

**Comment by ekse** [comment]
The server documentation says to copy this file before calling docker-compose, see the 'Important' section. I'm a bit unclear at the moment where to get this json config.

http://first-server.readthedocs.io/en/latest/

**Comment by demonduck** [comment]
@ekse To use Google's OAuth2 you will need to register with their developer console (https://console.developers.google.com), create a project, click Credentials, click Create Credentials, click OAuth Client ID, select Web application for application type and fill out the remainder of the form. Google will generate a json config that you can use to authenticate users through their OAuth service. 

Hope that helps
_demonduck

**Comment by demonduck** [comment]
Will update documentation to outline the steps to get a valid json config to enable Google OAuth

**Comment by demonduck** [comment]
Documentation updated in commit 422fd27

**Comment by jessie4736** [comment]
got an other error:
InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "web".
it seems there is no "redirect_uris" in google_secret.json

**Comment by demonduck** [comment]
@jessie4736, when you create your Client ID for web application you need to register authorized redirect URIs through Google's developer console. You will want to add the below redirect

`
http://my-personal-first-server.com/oauth/google
`

Make sure you specify the right protocol and domain. Unfortunately, iirc, you cannot specify an IP address, but you can use localhost.

**Comment by jessie4736** [comment]
@demonduck
got it! 
it works!
thanks very much!
